version: "3.9"

services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: euroloo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: euroloo
    volumes:
      - euroloo_pgdata:/var/lib/postgresql/data

volumes:
  euroloo_pgdata:
